[package]
name = "eiffel-tools"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"

[dependencies]
tree-sitter = "0.22.*"
tree-sitter-eiffel = { git = "https://github.com/imustafin/tree-sitter-eiffel", rev = "6566d7448d658dd61dc41f730902f61a61d40d9f"}
